server:
  port: 8878
spring:
  application:
    name: admin
  datasource:
    url: jdbc:mysql://192.168.151.99:3306/mo_middlePlatform?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8 
    username: root 
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid 
        login-password: druid
  flyway:
    enabled: true
    encoding: utf-8
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true
    table: flyway_schema_version_history
mybatis:
  mapper-locations: classpath:com/**/mapper/*.xml   # 指定sql映射文件位置
  config-location: classpath:mybatis-config.xml # 指定全局配置文件位置
